name: bwu_sparkline
version: 0.0.2
author: Günter Zöchbauer <guenter@gzoechbauer.com>
description: BWU Sparkline is A Polymer.dart port of jQuery Sparklines.
homepage: https://github.com/bwu-dart/bwu_sparkline
environment:
  sdk: '>=1.0.0 <2.0.0'
documentation: http://bwu-dart.github.io/bwu_sparkline/dartdoc/
environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  bwu_utils_browser: '>=0.0.2 <0.1.0'
#    path: ../../bwu_utils_browser
  polymer: '>=0.11.0-dev <0.12.0'
  quiver: '>=0.18.2 <0.19.0'
  quiver_log: '>=1.0.1 <2.0.0'

dev_dependencies:
  unittest: any

transformers:
- polymer:
    entry_points:
    - example/simple.html
